const { GoogleGenerativeAI } = require("@google/generative-ai");
const { redisClient } = require("../client/redis_client");
require("dotenv").config();
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

async function enrich(inp, email) {
  const rateLimitFlag = await redisClient.get(`RATE_LIMIT:ENRICH_TEXT:${email}`);
  if (rateLimitFlag) {
    throw new Error("Please wait before enriching more text.");
  }
  const model = genAI.getGenerativeModel({ model: "gemini-pro" });
  const prompt = `You are tasked with developing a web application that extracts text from PDF files, enriches it, and displays the processed results in an interactive table format. The application should have a seamless user interface for file uploads and should utilize Next.js/React.js/Node.js stack.
  Here is the text to be processed:
  ${inp}
  Please generate a response that includes the following:
  Enriched version of the provided text.
  Give Paragraphs well intended, with headings.
  Transform the text generated by gemini-pro, removing all instances of '*', and create a revised version without any asterisks
  `;
  const result = await model.generateContent(prompt);
  const response = await result.response;
  const text = response.text();
  text.replace("*", "");
  await redisClient.setex(`RATE_LIMIT:ENRICH_TEXT:${email}`, 60, 1); // Set rate limit for 60 seconds
  return text;
}

module.exports = { enrich };
